{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import random\n",
    "import gensim\n",
    "\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.metrics.pairwise import cosine_similarity"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Caricamento dei dati e creazione del modello"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "corpus = list()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open ('articoli.txt', 'r', encoding = 'utf-8') as file:\n",
    "    corpus = json.loads(file.read())\n",
    "    \n",
    "# eliminazione di quelle frasi che sono delle domande\n",
    "# (per evitare che il chatbot risponda con delle domande)\n",
    "for sentence in corpus:\n",
    "    if (sentence[len(sentence)-1] == '?'):\n",
    "        corpus.remove(sentence)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open('q&a.json', 'r') as data_structure:\n",
    "    q_a = json.load(data_structure)\n",
    "    # appendiamo le chiavi del dizionario (le domande delle FAQ)\n",
    "    for k in q_a.keys():\n",
    "        corpus.append(k)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "tfidf = TfidfVectorizer(ngram_range=(1, 3), min_df=2, max_df = 1000)\n",
    "# applichiamo il modello\n",
    "matrix_tfidf = tfidf.fit_transform(corpus)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# funzione che calcola e restituisce la cosine similarity tra\n",
    "# un vettore e la document-term matrix\n",
    "def compute_similarity (model, matrix, query):\n",
    "    vec_query = model.transform([query])\n",
    "    # flatten () rende la similarity matrix unidimensionale\n",
    "    cos_sim = cosine_similarity(vec_query, matrix).flatten()\n",
    "    \n",
    "    return cos_sim"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# funzione che restituisce un saluto come risposta a un saluto dell'utente\n",
    "def greeting_response(text):\n",
    "    text = text.lower()\n",
    "    \n",
    "    # lista dei possibili saluti che il bot può dare\n",
    "    bot_greetings = ['Ciao', 'Ehi']\n",
    "    # lista dei saluti che il bot riconosce\n",
    "    user_greetings = ['ciao']\n",
    "    \n",
    "    # se una parola dell'utente contiene una parola in user_greetings\n",
    "    for word in text.split():\n",
    "        if word in user_greetings:\n",
    "            # restituisci una parola presa a caso da bot_greetings\n",
    "            return random.choice(bot_greetings)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# funzione per riordinare una lista in ordine decrescente\n",
    "def index_sort(list_var):\n",
    "    length = len(list_var)\n",
    "    # creo una lista di indici per la lunghezza \n",
    "    # della lista passata. Questa lista verrà \n",
    "    # e riordinata e restituita  alla fine\n",
    "    list_index = list(range(0, length))\n",
    "    x = list_var\n",
    "    for i in range(length):\n",
    "        for j in range(length):\n",
    "            if x[list_index[i]] > x[list_index[j]]:\n",
    "                # scambio gli elementi\n",
    "                temp = list_index[i]\n",
    "                list_index[i] = list_index[j]\n",
    "                list_index[j] = temp\n",
    "                \n",
    "    return list_index"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def bot_response(user_input, model, matrix, q_a):\n",
    "    bot_response = ''\n",
    "    # flag per vedere se esiste una risposta per la query dell'utente\n",
    "    response_flag = 0\n",
    "    \n",
    "    similarity_scores_list = compute_similarity(model, matrix, user_input)\n",
    "    # index = lista di indici riodinati a seconda del similarity score\n",
    "    index = index_sort(similarity_scores_list)\n",
    "    \n",
    "    # contatore per attaccare solo la prima risposta \n",
    "    # che abbia similarity score > 0.0\n",
    "    j = 0\n",
    "    for i in range(len(index)):\n",
    "        if j >= 1:\n",
    "            break\n",
    "        # se il similarity score è maggiore di 0, \n",
    "        # significa una risposta esiste\n",
    "        if similarity_scores_list[index[i]] > 0.0:\n",
    "            # se la frase più simile che ha trovato è una domanda delle FAQ\n",
    "            # restituisco la risposta\n",
    "            if corpus[index[i]] in q_a.keys():\n",
    "                bot_response = bot_response + q_a[corpus[index[i]]][0]\n",
    "                response_flag = 1 # abbiamo trovato la risposta\n",
    "                j = j + 1 # aggiorno il contatore per ogni risposta trovata\n",
    "            # altrimenti, prende una frase degli articoli\n",
    "            else:\n",
    "                bot_response = bot_response + corpus[index[i]]\n",
    "                response_flag = 1 # abbiamo trovato la risposta\n",
    "                j = j + 1 # aggiorno il contatore per ogni risposta trovata\n",
    "\n",
    "    # se non abbiamo trovato una risposta\n",
    "    if response_flag == 0:\n",
    "        bot_response = bot_response + 'Scusa, non sono in grado di risponderti.'\n",
    "\n",
    "    return bot_response"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Bot construction"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: telepot in c:\\users\\asus\\anaconda3\\lib\\site-packages (12.7)\n",
      "Requirement already satisfied: urllib3>=1.9.1 in c:\\users\\asus\\anaconda3\\lib\\site-packages (from telepot) (1.25.9)\n",
      "Requirement already satisfied: aiohttp>=3.0.0 in c:\\users\\asus\\anaconda3\\lib\\site-packages (from telepot) (3.7.3)\n",
      "Requirement already satisfied: typing-extensions>=3.6.5 in c:\\users\\asus\\anaconda3\\lib\\site-packages (from aiohttp>=3.0.0->telepot) (3.7.4.2)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in c:\\users\\asus\\anaconda3\\lib\\site-packages (from aiohttp>=3.0.0->telepot) (1.6.3)\n",
      "Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\\users\\asus\\anaconda3\\lib\\site-packages (from aiohttp>=3.0.0->telepot) (3.0.1)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in c:\\users\\asus\\anaconda3\\lib\\site-packages (from aiohttp>=3.0.0->telepot) (5.1.0)\n",
      "Requirement already satisfied: chardet<4.0,>=2.0 in c:\\users\\asus\\anaconda3\\lib\\site-packages (from aiohttp>=3.0.0->telepot) (3.0.4)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\users\\asus\\anaconda3\\lib\\site-packages (from aiohttp>=3.0.0->telepot) (19.3.0)\n",
      "Requirement already satisfied: idna>=2.0 in c:\\users\\asus\\anaconda3\\lib\\site-packages (from yarl<2.0,>=1.0->aiohttp>=3.0.0->telepot) (2.10)\n"
     ]
    }
   ],
   "source": [
    "!pip install telepot"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1181, in get_from_telegram_server\n",
      "    result = self.getUpdates(offset=offset,\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"C:\\Users\\ASUS\\anaconda3\\lib\\site-packages\\telepot\\api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-12-30cca77849b5>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     26\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     27\u001b[0m \u001b[1;32mwhile\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 28\u001b[1;33m     \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m10\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;31m#ciclo infinito per farlo runnare in continuazione\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "# in questa cella si stabilisce il collegamento con la API del chatbot creato e si manda in ciclo infinito\n",
    "#### NB: di solito il programma deve essere interrotto e la cella ri-runnata per attivare il chatbot ####\n",
    "import telepot\n",
    "import time\n",
    "\n",
    "def on_chat_message(msg):\n",
    "    user_input = msg[\"text\"]\n",
    "    answer = ''\n",
    "    content_type, chat_type, chat_id = telepot.glance(msg)\n",
    "    if content_type == 'text':\n",
    "        name = msg[\"from\"][\"first_name\"] # questa riga serve nel caso vogliamo recuperare il nome dell'utente e passarlo\n",
    "        if greeting_response(user_input) != None:\n",
    "            answer = greeting_response(user_input)\n",
    "            # qui invoca la funzione chatbot response\n",
    "            bot.sendMessage(chat_id, answer) # invocare la nostra funzione\n",
    "        else:\n",
    "            answer = bot_response(user_input, tfidf, matrix_tfidf, q_a)\n",
    "            bot.sendMessage(chat_id, answer)\n",
    "    else:\n",
    "        bot.sendMessage(chat_id, 'Perdonami, per ora posso leggere solo testi scritti...'%name)\n",
    "\n",
    "TOKEN = '1699693493:AAGGQgV4Wd84wOAmMqHDzf09c51osqoGk60' # il token associato a BotFather\n",
    "\n",
    "bot = telepot.Bot(TOKEN)\n",
    "bot.message_loop(on_chat_message)\n",
    "\n",
    "while True:\n",
    "    time.sleep(10) #ciclo infinito per farlo runnare in continuazione"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
